Add triggers
jaimerson/db_imd_0401_projeto_final pull request #2
Opened 2017-11-18 17:59 UTC by dhdo

2017-11-19 08:22 UTC, jaimerson approved these changes

2017-11-19 12:48 UTC, jaimerson requested changes

2017-11-19 12:48 UTC, jaimerson commented on db/queries/create_tables.sql
> +    RAISE EXCEPTION 'Duração de uma legislatura não pode ser maior que 4 anos.';
Isso dá erro com os dados que temos ¯\\_(ツ)\_\/¯
Temos que achar outra validação pra usar um trigger.

2017-11-20 02:20 UTC, dhdo commented on db/queries/create_tables.sql
> +    RAISE EXCEPTION 'Duração de uma legislatura não pode ser maior que 4 anos.';
Vou aumentar a precisão para levar em consideração os dias

2017-11-22 17:04 UTC, closed without merging